### ISSUE TITLE
Completed module 6 assignment 2

### ISSUE THREAD

**Issue by sprinz11** [rbtl-fs24/md-06-assignments-sprinz11#1]
Hi @larnsce 

Similar to your png plot that had to be recreated, in my figure the label for the income catergories are sorted according to the factor created before.
However, the bars in the figure are ordered in the opposite way than I would have liked them to be (low income on the top and high income on the bottom). Is there a way to adjust that? I wasn't able to figure it out.
Thanks :)
![46615a9e-5379-44d9-ab27-1c7b2596b034](https://github.com/rbtl-fs24/md-06-assignments-sprinz11/assets/114858201/5c8f0fd1-4c44-40c7-8953-a4ee2fe21ebf)

**Comment by larnsce** [comment]
Thanks for your patience, @sprinz11.

I have two sources for you:

- Perplexity: https://www.perplexity.ai/search/In-R-ggplot-NTjU8yi3QZGkveLa2sVx.A
- A gist by Jenny Bryan: https://gist.github.com/jennybc/847c6b43c4e35cec2e5bb30a3f38af73
